logging:
  level:
    root: INFO
    dev.berke.app.auth: ${APP_LOG_LEVEL:INFO}
server:
  port: 8030
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379
token:
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 86400000
