logging:
  level:
    root: INFO
    dev.berke.app.customer: ${APP_LOG_LEVEL:INFO}
server:
  port: 8090
spring:
  data:
    mongodb:
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
